name: e2e tests

on:
  push:
    branches:
      - master
      - '**Tests**'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'  

jobs:
  test-setup-python:
    name: Test setup-python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run with setup-python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'
      - name: Setup pylint
        run: python -m pip install pylint
      - name: Setup flake8
        run: python -m pip install flake8            
      - name: Run tests
        run: python -m unittest discover -s segment

      - name: Run with setup-python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Setup pylint
        run: python -m pip install pylint
      - name: Setup flake8
        run: python -m pip install flake8            
      - name: Run tests
        run: python -m unittest discover -s segment

      - name: Run with setup-python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Setup pylint
        run: python -m pip install pylint
      - name: Setup flake8
        run: python -m pip install flake8            
      - name: Run tests
        run: python -m unittest discover -s segment

      - name: Run with setup-python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Setup pylint
        run: python -m pip install pylint
      - name: Setup flake8
        run: python -m pip install flake8            
      - name: Run tests
        run: python -m unittest discover -s segment
        
      - name: Run with setup-python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup pylint
        run: python -m pip install pylint
      - name: Setup flake8
        run: python -m pip install flake8            
      - name: Run tests
        run: python -m unittest discover -s segment